# Generated by Django 5.1.1 on 2024-09-25 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название организации', max_length=255, verbose_name='Название организации')),
                ('email', models.EmailField(help_text='Введите вашу электронную почту', max_length=254, verbose_name='Email')),
                ('country', models.CharField(help_text='Введите страну', max_length=100, verbose_name='Страна')),
                ('city', models.CharField(help_text='Введите город', max_length=100, verbose_name='Город')),
                ('street', models.CharField(help_text='Введите улицу', max_length=100, verbose_name='Улица')),
                ('house_number', models.CharField(help_text='Введите номер дома', max_length=10, verbose_name='Номер дома')),
                ('product_name', models.CharField(help_text='Введите название продукта', max_length=255, verbose_name='Название продукта')),
                ('product_model', models.CharField(help_text='Введите модель продукта', max_length=255, verbose_name='Модель продукта')),
                ('product_release_date', models.DateField(help_text='Введите дату выпуска продукта', verbose_name='Дата выпуска продукта')),
                ('debt', models.DecimalField(decimal_places=2, help_text='Введите текущий долг', max_digits=10, verbose_name='Долг')),
                ('level', models.IntegerField(choices=[(0, 'Завод'), (1, 'Розничная сеть'), (2, 'Индивидуальный предприниматель')], help_text='Выберите уровень организации', verbose_name='Уровень организации')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Время создания записи', verbose_name='Дата создания')),
                ('supplier', models.ForeignKey(blank=True, help_text='Выберите поставщика', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='network.networknode', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Торговая сеть',
                'verbose_name_plural': 'Торговые сети',
            },
        ),
    ]
